spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liMl6oQwf8rLXlf4
            client-secret: 3fb2710489ab34d0b8ebb562cb91e51c4b61843b
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000    # 5 min
      max-lifetime: 1800000   # 30 min
      connection-timeout: 30000 # 30 s
      leak-detection-threshold: 2000  # 2 s
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
  cache:
    type: simple
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server:
          requests: true
